### ISSUE TITLE
Problem with instalation

### ISSUE THREAD

**Issue by jsbalanzar** [SkypLabs/python-hdlc-controller#9]
Hello,

First, thanks for share your proyect. I will try to test but the instalation has a problem.

![image](https://user-images.githubusercontent.com/53954505/77879183-0ad88e00-7217-11ea-8855-e98b12d51a9e.png)

I do teh upgrade of the setuptools and wheel, but I can't solve this problem, Could you help me please?

Thanks
Juan Carlos

**Comment by SkypLabs** [comment]
Hi Juan,

Thanks for your interest in my project.

The issue comes from the installation of [python4yahdlc][python4yahdlc], a dependency of python-hdlc-controller that I have written as well. The installation problem occurs on Windows only and is already known: https://github.com/SkypLabs/python4yahdlc/issues/3.

Unfortunately, I haven't found the time to issue a fix so far. I've been really busy at work since last year but it will change pretty soon. I'm about to become a freelancer. I will have plenty of time to work on a fix from next month onwards. Please be a little bit patient on this one.

Thank you for your understanding.

 [python4yahdlc]: https://github.com/SkypLabs/python4yahdlc

**Comment by SkypLabs** [comment]
I just fixed the issue about installing python4yahdlc on Windows, which means the installation problem of python-hdlc-controller will be fixed as well as soon as the new release version of python4yahdlc is available on PyPI (very soon).

**Comment by SkypLabs** [comment]
I just released version 0.5.2 on PyPI. This should fix the installation problem on Windows.
